[2022-01-19 11:42:21,425] {processor.py:163} INFO - Started process (PID=277) to work on /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 11:42:21,429] {processor.py:620} INFO - Processing file /opt/airflow/dags/MySQL_to_Redshift_v3.py for tasks to queue
[2022-01-19 11:42:21,432] {logging_mixin.py:109} INFO - [2022-01-19 11:42:21,432] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 11:42:21,449] {logging_mixin.py:109} INFO - [2022-01-19 11:42:21,446] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/MySQL_to_Redshift_v3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/MySQL_to_Redshift_v3.py", line 75
    dag = dag
      ^
SyntaxError: invalid syntax
[2022-01-19 11:42:21,482] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 11:42:21,501] {processor.py:171} INFO - Processing /opt/airflow/dags/MySQL_to_Redshift_v3.py took 0.084 seconds
[2022-01-19 11:45:32,052] {processor.py:163} INFO - Started process (PID=728) to work on /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 11:45:32,057] {processor.py:620} INFO - Processing file /opt/airflow/dags/MySQL_to_Redshift_v3.py for tasks to queue
[2022-01-19 11:45:32,061] {logging_mixin.py:109} INFO - [2022-01-19 11:45:32,060] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 11:45:32,080] {logging_mixin.py:109} INFO - [2022-01-19 11:45:32,076] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/MySQL_to_Redshift_v3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/MySQL_to_Redshift_v3.py", line 75
    dag = dag
      ^
SyntaxError: invalid syntax
[2022-01-19 11:45:32,122] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 11:45:32,145] {processor.py:171} INFO - Processing /opt/airflow/dags/MySQL_to_Redshift_v3.py took 0.101 seconds
[2022-01-19 11:46:02,399] {processor.py:163} INFO - Started process (PID=850) to work on /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 11:46:02,403] {processor.py:620} INFO - Processing file /opt/airflow/dags/MySQL_to_Redshift_v3.py for tasks to queue
[2022-01-19 11:46:02,406] {logging_mixin.py:109} INFO - [2022-01-19 11:46:02,406] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 11:46:02,423] {logging_mixin.py:109} INFO - [2022-01-19 11:46:02,420] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/MySQL_to_Redshift_v3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/MySQL_to_Redshift_v3.py", line 75
    dag = dag
      ^
SyntaxError: invalid syntax
[2022-01-19 11:46:02,455] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 11:46:02,474] {processor.py:171} INFO - Processing /opt/airflow/dags/MySQL_to_Redshift_v3.py took 0.082 seconds
[2022-01-19 11:46:33,299] {processor.py:163} INFO - Started process (PID=996) to work on /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 11:46:33,303] {processor.py:620} INFO - Processing file /opt/airflow/dags/MySQL_to_Redshift_v3.py for tasks to queue
[2022-01-19 11:46:33,306] {logging_mixin.py:109} INFO - [2022-01-19 11:46:33,305] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 11:46:33,322] {logging_mixin.py:109} INFO - [2022-01-19 11:46:33,319] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/MySQL_to_Redshift_v3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/MySQL_to_Redshift_v3.py", line 75
    dag = dag
      ^
SyntaxError: invalid syntax
[2022-01-19 11:46:33,357] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 11:46:33,377] {processor.py:171} INFO - Processing /opt/airflow/dags/MySQL_to_Redshift_v3.py took 0.086 seconds
[2022-01-19 11:47:04,025] {processor.py:163} INFO - Started process (PID=1122) to work on /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 11:47:04,029] {processor.py:620} INFO - Processing file /opt/airflow/dags/MySQL_to_Redshift_v3.py for tasks to queue
[2022-01-19 11:47:04,031] {logging_mixin.py:109} INFO - [2022-01-19 11:47:04,031] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 11:47:04,046] {logging_mixin.py:109} INFO - [2022-01-19 11:47:04,043] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/MySQL_to_Redshift_v3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/MySQL_to_Redshift_v3.py", line 75
    dag = dag
      ^
SyntaxError: invalid syntax
[2022-01-19 11:47:04,076] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 11:47:04,094] {processor.py:171} INFO - Processing /opt/airflow/dags/MySQL_to_Redshift_v3.py took 0.075 seconds
[2022-01-19 11:47:35,617] {processor.py:163} INFO - Started process (PID=1266) to work on /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 11:47:35,622] {processor.py:620} INFO - Processing file /opt/airflow/dags/MySQL_to_Redshift_v3.py for tasks to queue
[2022-01-19 11:47:35,626] {logging_mixin.py:109} INFO - [2022-01-19 11:47:35,626] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 11:47:35,653] {logging_mixin.py:109} INFO - [2022-01-19 11:47:35,639] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/MySQL_to_Redshift_v3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/MySQL_to_Redshift_v3.py", line 75
    dag = dag
      ^
SyntaxError: invalid syntax
[2022-01-19 11:47:35,718] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 11:47:35,741] {processor.py:171} INFO - Processing /opt/airflow/dags/MySQL_to_Redshift_v3.py took 0.131 seconds
[2022-01-19 11:48:07,564] {processor.py:163} INFO - Started process (PID=1403) to work on /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 11:48:07,569] {processor.py:620} INFO - Processing file /opt/airflow/dags/MySQL_to_Redshift_v3.py for tasks to queue
[2022-01-19 11:48:07,572] {logging_mixin.py:109} INFO - [2022-01-19 11:48:07,571] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 11:48:07,591] {logging_mixin.py:109} INFO - [2022-01-19 11:48:07,587] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/MySQL_to_Redshift_v3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/MySQL_to_Redshift_v3.py", line 75
    dag = dag
      ^
SyntaxError: invalid syntax
[2022-01-19 11:48:07,627] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 11:48:07,648] {processor.py:171} INFO - Processing /opt/airflow/dags/MySQL_to_Redshift_v3.py took 0.092 seconds
[2022-01-19 11:48:38,751] {processor.py:163} INFO - Started process (PID=1536) to work on /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 11:48:38,756] {processor.py:620} INFO - Processing file /opt/airflow/dags/MySQL_to_Redshift_v3.py for tasks to queue
[2022-01-19 11:48:38,759] {logging_mixin.py:109} INFO - [2022-01-19 11:48:38,759] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 11:48:38,780] {logging_mixin.py:109} INFO - [2022-01-19 11:48:38,776] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/MySQL_to_Redshift_v3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/MySQL_to_Redshift_v3.py", line 75
    dag = dag
      ^
SyntaxError: invalid syntax
[2022-01-19 11:48:38,812] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 11:48:38,832] {processor.py:171} INFO - Processing /opt/airflow/dags/MySQL_to_Redshift_v3.py took 0.087 seconds
[2022-01-19 11:49:08,949] {processor.py:163} INFO - Started process (PID=1672) to work on /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 11:49:08,953] {processor.py:620} INFO - Processing file /opt/airflow/dags/MySQL_to_Redshift_v3.py for tasks to queue
[2022-01-19 11:49:08,956] {logging_mixin.py:109} INFO - [2022-01-19 11:49:08,955] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 11:49:08,978] {logging_mixin.py:109} INFO - [2022-01-19 11:49:08,974] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/MySQL_to_Redshift_v3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/MySQL_to_Redshift_v3.py", line 75
    dag = dag
      ^
SyntaxError: invalid syntax
[2022-01-19 11:49:09,012] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 11:49:09,036] {processor.py:171} INFO - Processing /opt/airflow/dags/MySQL_to_Redshift_v3.py took 0.095 seconds
[2022-01-19 11:49:40,008] {processor.py:163} INFO - Started process (PID=1800) to work on /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 11:49:40,012] {processor.py:620} INFO - Processing file /opt/airflow/dags/MySQL_to_Redshift_v3.py for tasks to queue
[2022-01-19 11:49:40,015] {logging_mixin.py:109} INFO - [2022-01-19 11:49:40,014] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 11:49:40,031] {logging_mixin.py:109} INFO - [2022-01-19 11:49:40,028] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/MySQL_to_Redshift_v3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/MySQL_to_Redshift_v3.py", line 75
    dag = dag
      ^
SyntaxError: invalid syntax
[2022-01-19 11:49:40,065] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 11:49:40,083] {processor.py:171} INFO - Processing /opt/airflow/dags/MySQL_to_Redshift_v3.py took 0.083 seconds
[2022-01-19 11:50:10,859] {processor.py:163} INFO - Started process (PID=1945) to work on /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 11:50:10,864] {processor.py:620} INFO - Processing file /opt/airflow/dags/MySQL_to_Redshift_v3.py for tasks to queue
[2022-01-19 11:50:10,867] {logging_mixin.py:109} INFO - [2022-01-19 11:50:10,866] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 11:50:10,885] {logging_mixin.py:109} INFO - [2022-01-19 11:50:10,882] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/MySQL_to_Redshift_v3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/MySQL_to_Redshift_v3.py", line 75
    dag = dag
      ^
SyntaxError: invalid syntax
[2022-01-19 11:50:10,918] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 11:50:10,938] {processor.py:171} INFO - Processing /opt/airflow/dags/MySQL_to_Redshift_v3.py took 0.088 seconds
[2022-01-19 11:50:42,166] {processor.py:163} INFO - Started process (PID=2061) to work on /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 11:50:42,170] {processor.py:620} INFO - Processing file /opt/airflow/dags/MySQL_to_Redshift_v3.py for tasks to queue
[2022-01-19 11:50:42,175] {logging_mixin.py:109} INFO - [2022-01-19 11:50:42,174] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 11:50:42,201] {logging_mixin.py:109} INFO - [2022-01-19 11:50:42,197] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/MySQL_to_Redshift_v3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/MySQL_to_Redshift_v3.py", line 75
    dag = dag
      ^
SyntaxError: invalid syntax
[2022-01-19 11:50:42,243] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 11:50:42,265] {processor.py:171} INFO - Processing /opt/airflow/dags/MySQL_to_Redshift_v3.py took 0.108 seconds
[2022-01-19 11:54:23,555] {processor.py:163} INFO - Started process (PID=193) to work on /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 11:54:23,586] {processor.py:620} INFO - Processing file /opt/airflow/dags/MySQL_to_Redshift_v3.py for tasks to queue
[2022-01-19 11:54:23,599] {logging_mixin.py:109} INFO - [2022-01-19 11:54:23,598] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 11:54:23,631] {logging_mixin.py:109} INFO - [2022-01-19 11:54:23,623] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/MySQL_to_Redshift_v3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/MySQL_to_Redshift_v3.py", line 75
    dag = dag
      ^
SyntaxError: invalid syntax
[2022-01-19 11:54:23,716] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 11:54:23,758] {processor.py:171} INFO - Processing /opt/airflow/dags/MySQL_to_Redshift_v3.py took 0.240 seconds
[2022-01-19 11:55:04,392] {processor.py:163} INFO - Started process (PID=337) to work on /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 11:55:04,397] {processor.py:620} INFO - Processing file /opt/airflow/dags/MySQL_to_Redshift_v3.py for tasks to queue
[2022-01-19 11:55:04,400] {logging_mixin.py:109} INFO - [2022-01-19 11:55:04,400] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 11:55:04,430] {logging_mixin.py:109} INFO - [2022-01-19 11:55:04,426] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/MySQL_to_Redshift_v3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/MySQL_to_Redshift_v3.py", line 75
    dag = dag
      ^
SyntaxError: invalid syntax
[2022-01-19 11:55:04,519] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 11:55:04,582] {processor.py:171} INFO - Processing /opt/airflow/dags/MySQL_to_Redshift_v3.py took 0.219 seconds
[2022-01-19 11:55:35,106] {processor.py:163} INFO - Started process (PID=463) to work on /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 11:55:35,112] {processor.py:620} INFO - Processing file /opt/airflow/dags/MySQL_to_Redshift_v3.py for tasks to queue
[2022-01-19 11:55:35,115] {logging_mixin.py:109} INFO - [2022-01-19 11:55:35,115] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 11:55:35,135] {logging_mixin.py:109} INFO - [2022-01-19 11:55:35,132] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/MySQL_to_Redshift_v3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/MySQL_to_Redshift_v3.py", line 75
    dag = dag
      ^
SyntaxError: invalid syntax
[2022-01-19 11:55:35,166] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 11:55:35,183] {processor.py:171} INFO - Processing /opt/airflow/dags/MySQL_to_Redshift_v3.py took 0.085 seconds
[2022-01-19 11:56:05,653] {processor.py:163} INFO - Started process (PID=604) to work on /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 11:56:05,662] {processor.py:620} INFO - Processing file /opt/airflow/dags/MySQL_to_Redshift_v3.py for tasks to queue
[2022-01-19 11:56:05,667] {logging_mixin.py:109} INFO - [2022-01-19 11:56:05,667] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 11:56:05,695] {logging_mixin.py:109} INFO - [2022-01-19 11:56:05,687] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/MySQL_to_Redshift_v3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/MySQL_to_Redshift_v3.py", line 75
    dag = dag
      ^
SyntaxError: invalid syntax
[2022-01-19 11:56:05,738] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 11:56:05,758] {processor.py:171} INFO - Processing /opt/airflow/dags/MySQL_to_Redshift_v3.py took 0.116 seconds
[2022-01-19 11:56:35,965] {processor.py:163} INFO - Started process (PID=730) to work on /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 11:56:35,969] {processor.py:620} INFO - Processing file /opt/airflow/dags/MySQL_to_Redshift_v3.py for tasks to queue
[2022-01-19 11:56:35,971] {logging_mixin.py:109} INFO - [2022-01-19 11:56:35,971] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 11:56:35,986] {logging_mixin.py:109} INFO - [2022-01-19 11:56:35,983] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/MySQL_to_Redshift_v3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/MySQL_to_Redshift_v3.py", line 75
    dag = dag
      ^
SyntaxError: invalid syntax
[2022-01-19 11:56:36,016] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 11:56:36,036] {processor.py:171} INFO - Processing /opt/airflow/dags/MySQL_to_Redshift_v3.py took 0.077 seconds
[2022-01-19 11:57:06,571] {processor.py:163} INFO - Started process (PID=876) to work on /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 11:57:06,580] {processor.py:620} INFO - Processing file /opt/airflow/dags/MySQL_to_Redshift_v3.py for tasks to queue
[2022-01-19 11:57:06,584] {logging_mixin.py:109} INFO - [2022-01-19 11:57:06,583] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 11:57:06,610] {logging_mixin.py:109} INFO - [2022-01-19 11:57:06,606] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/MySQL_to_Redshift_v3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/MySQL_to_Redshift_v3.py", line 75
    dag = dag
      ^
SyntaxError: invalid syntax
[2022-01-19 11:57:06,681] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 11:57:06,746] {processor.py:171} INFO - Processing /opt/airflow/dags/MySQL_to_Redshift_v3.py took 0.183 seconds
[2022-01-19 11:57:36,793] {processor.py:163} INFO - Started process (PID=1001) to work on /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 11:57:36,797] {processor.py:620} INFO - Processing file /opt/airflow/dags/MySQL_to_Redshift_v3.py for tasks to queue
[2022-01-19 11:57:36,799] {logging_mixin.py:109} INFO - [2022-01-19 11:57:36,799] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 11:57:36,815] {logging_mixin.py:109} INFO - [2022-01-19 11:57:36,812] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/MySQL_to_Redshift_v3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/MySQL_to_Redshift_v3.py", line 75
    dag = dag
      ^
SyntaxError: invalid syntax
[2022-01-19 11:57:36,845] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 11:57:36,860] {processor.py:171} INFO - Processing /opt/airflow/dags/MySQL_to_Redshift_v3.py took 0.074 seconds
[2022-01-19 11:58:07,665] {processor.py:163} INFO - Started process (PID=1143) to work on /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 11:58:07,670] {processor.py:620} INFO - Processing file /opt/airflow/dags/MySQL_to_Redshift_v3.py for tasks to queue
[2022-01-19 11:58:07,674] {logging_mixin.py:109} INFO - [2022-01-19 11:58:07,674] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 11:58:07,691] {logging_mixin.py:109} INFO - [2022-01-19 11:58:07,688] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/MySQL_to_Redshift_v3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/MySQL_to_Redshift_v3.py", line 75
    dag = dag
      ^
SyntaxError: invalid syntax
[2022-01-19 11:58:07,728] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 11:58:07,757] {processor.py:171} INFO - Processing /opt/airflow/dags/MySQL_to_Redshift_v3.py took 0.100 seconds
[2022-01-19 11:58:19,419] {processor.py:163} INFO - Started process (PID=1185) to work on /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 11:58:19,425] {processor.py:620} INFO - Processing file /opt/airflow/dags/MySQL_to_Redshift_v3.py for tasks to queue
[2022-01-19 11:58:19,428] {logging_mixin.py:109} INFO - [2022-01-19 11:58:19,427] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 11:58:19,446] {logging_mixin.py:109} INFO - [2022-01-19 11:58:19,442] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/MySQL_to_Redshift_v3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/MySQL_to_Redshift_v3.py", line 75
    dag = dag
      ^
SyntaxError: invalid syntax
[2022-01-19 11:58:19,485] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 11:58:19,505] {processor.py:171} INFO - Processing /opt/airflow/dags/MySQL_to_Redshift_v3.py took 0.094 seconds
[2022-01-19 11:58:30,261] {processor.py:163} INFO - Started process (PID=1287) to work on /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 11:58:30,265] {processor.py:620} INFO - Processing file /opt/airflow/dags/MySQL_to_Redshift_v3.py for tasks to queue
[2022-01-19 11:58:30,269] {logging_mixin.py:109} INFO - [2022-01-19 11:58:30,268] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 11:58:30,285] {logging_mixin.py:109} INFO - [2022-01-19 11:58:30,282] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/MySQL_to_Redshift_v3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/MySQL_to_Redshift_v3.py", line 75
    dag = dag
      ^
SyntaxError: invalid syntax
[2022-01-19 11:58:30,329] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 11:58:30,358] {processor.py:171} INFO - Processing /opt/airflow/dags/MySQL_to_Redshift_v3.py took 0.105 seconds
[2022-01-19 12:04:19,871] {processor.py:163} INFO - Started process (PID=2494) to work on /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 12:04:19,877] {processor.py:620} INFO - Processing file /opt/airflow/dags/MySQL_to_Redshift_v3.py for tasks to queue
[2022-01-19 12:04:19,880] {logging_mixin.py:109} INFO - [2022-01-19 12:04:19,880] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 12:04:19,903] {logging_mixin.py:109} INFO - [2022-01-19 12:04:19,900] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/MySQL_to_Redshift_v3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/MySQL_to_Redshift_v3.py", line 75
    dag = dag
      ^
SyntaxError: invalid syntax
[2022-01-19 12:04:19,937] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 12:04:19,957] {processor.py:171} INFO - Processing /opt/airflow/dags/MySQL_to_Redshift_v3.py took 0.094 seconds
[2022-01-19 12:04:50,720] {processor.py:163} INFO - Started process (PID=2611) to work on /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 12:04:50,724] {processor.py:620} INFO - Processing file /opt/airflow/dags/MySQL_to_Redshift_v3.py for tasks to queue
[2022-01-19 12:04:50,728] {logging_mixin.py:109} INFO - [2022-01-19 12:04:50,727] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 12:04:50,746] {logging_mixin.py:109} INFO - [2022-01-19 12:04:50,742] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/MySQL_to_Redshift_v3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/MySQL_to_Redshift_v3.py", line 75
    dag = dag
      ^
SyntaxError: invalid syntax
[2022-01-19 12:04:50,778] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 12:04:50,795] {processor.py:171} INFO - Processing /opt/airflow/dags/MySQL_to_Redshift_v3.py took 0.082 seconds
[2022-01-19 12:05:21,990] {processor.py:163} INFO - Started process (PID=2750) to work on /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 12:05:21,996] {processor.py:620} INFO - Processing file /opt/airflow/dags/MySQL_to_Redshift_v3.py for tasks to queue
[2022-01-19 12:05:22,000] {logging_mixin.py:109} INFO - [2022-01-19 12:05:22,000] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 12:05:22,019] {logging_mixin.py:109} INFO - [2022-01-19 12:05:22,015] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/MySQL_to_Redshift_v3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/MySQL_to_Redshift_v3.py", line 75
    dag = dag
      ^
SyntaxError: invalid syntax
[2022-01-19 12:05:22,088] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 12:05:22,109] {processor.py:171} INFO - Processing /opt/airflow/dags/MySQL_to_Redshift_v3.py took 0.127 seconds
[2022-01-19 12:05:52,294] {processor.py:163} INFO - Started process (PID=2872) to work on /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 12:05:52,298] {processor.py:620} INFO - Processing file /opt/airflow/dags/MySQL_to_Redshift_v3.py for tasks to queue
[2022-01-19 12:05:52,301] {logging_mixin.py:109} INFO - [2022-01-19 12:05:52,301] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 12:05:52,318] {logging_mixin.py:109} INFO - [2022-01-19 12:05:52,314] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/MySQL_to_Redshift_v3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/MySQL_to_Redshift_v3.py", line 75
    dag = dag
      ^
SyntaxError: invalid syntax
[2022-01-19 12:05:52,348] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 12:05:52,368] {processor.py:171} INFO - Processing /opt/airflow/dags/MySQL_to_Redshift_v3.py took 0.081 seconds
[2022-01-19 12:06:23,009] {processor.py:163} INFO - Started process (PID=3010) to work on /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 12:06:23,013] {processor.py:620} INFO - Processing file /opt/airflow/dags/MySQL_to_Redshift_v3.py for tasks to queue
[2022-01-19 12:06:23,017] {logging_mixin.py:109} INFO - [2022-01-19 12:06:23,016] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 12:06:23,033] {logging_mixin.py:109} INFO - [2022-01-19 12:06:23,030] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/MySQL_to_Redshift_v3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/MySQL_to_Redshift_v3.py", line 75
    dag = dag
      ^
SyntaxError: invalid syntax
[2022-01-19 12:06:23,071] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 12:06:23,090] {processor.py:171} INFO - Processing /opt/airflow/dags/MySQL_to_Redshift_v3.py took 0.089 seconds
[2022-01-19 12:06:53,328] {processor.py:163} INFO - Started process (PID=3131) to work on /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 12:06:53,332] {processor.py:620} INFO - Processing file /opt/airflow/dags/MySQL_to_Redshift_v3.py for tasks to queue
[2022-01-19 12:06:53,335] {logging_mixin.py:109} INFO - [2022-01-19 12:06:53,335] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 12:06:53,350] {logging_mixin.py:109} INFO - [2022-01-19 12:06:53,347] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/MySQL_to_Redshift_v3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/MySQL_to_Redshift_v3.py", line 75
    dag = dag
      ^
SyntaxError: invalid syntax
[2022-01-19 12:06:53,384] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 12:06:53,402] {processor.py:171} INFO - Processing /opt/airflow/dags/MySQL_to_Redshift_v3.py took 0.081 seconds
[2022-01-19 12:07:24,056] {processor.py:163} INFO - Started process (PID=3269) to work on /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 12:07:24,060] {processor.py:620} INFO - Processing file /opt/airflow/dags/MySQL_to_Redshift_v3.py for tasks to queue
[2022-01-19 12:07:24,064] {logging_mixin.py:109} INFO - [2022-01-19 12:07:24,063] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 12:07:24,081] {logging_mixin.py:109} INFO - [2022-01-19 12:07:24,078] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/MySQL_to_Redshift_v3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/MySQL_to_Redshift_v3.py", line 75
    dag = dag
      ^
SyntaxError: invalid syntax
[2022-01-19 12:07:24,112] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 12:07:24,130] {processor.py:171} INFO - Processing /opt/airflow/dags/MySQL_to_Redshift_v3.py took 0.082 seconds
[2022-01-19 12:07:54,662] {processor.py:163} INFO - Started process (PID=3390) to work on /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 12:07:54,666] {processor.py:620} INFO - Processing file /opt/airflow/dags/MySQL_to_Redshift_v3.py for tasks to queue
[2022-01-19 12:07:54,668] {logging_mixin.py:109} INFO - [2022-01-19 12:07:54,668] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 12:07:54,685] {logging_mixin.py:109} INFO - [2022-01-19 12:07:54,682] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/MySQL_to_Redshift_v3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/MySQL_to_Redshift_v3.py", line 75
    dag = dag
      ^
SyntaxError: invalid syntax
[2022-01-19 12:07:54,718] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 12:07:54,736] {processor.py:171} INFO - Processing /opt/airflow/dags/MySQL_to_Redshift_v3.py took 0.081 seconds
[2022-01-19 12:08:25,090] {processor.py:163} INFO - Started process (PID=3527) to work on /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 12:08:25,095] {processor.py:620} INFO - Processing file /opt/airflow/dags/MySQL_to_Redshift_v3.py for tasks to queue
[2022-01-19 12:08:25,098] {logging_mixin.py:109} INFO - [2022-01-19 12:08:25,097] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 12:08:25,114] {logging_mixin.py:109} INFO - [2022-01-19 12:08:25,110] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/MySQL_to_Redshift_v3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/MySQL_to_Redshift_v3.py", line 75
    dag = dag
      ^
SyntaxError: invalid syntax
[2022-01-19 12:08:25,145] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 12:08:25,164] {processor.py:171} INFO - Processing /opt/airflow/dags/MySQL_to_Redshift_v3.py took 0.082 seconds
[2022-01-19 12:10:00,159] {processor.py:163} INFO - Started process (PID=3839) to work on /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 12:10:00,164] {processor.py:620} INFO - Processing file /opt/airflow/dags/MySQL_to_Redshift_v3.py for tasks to queue
[2022-01-19 12:10:00,167] {logging_mixin.py:109} INFO - [2022-01-19 12:10:00,167] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 12:10:00,211] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/MySQL_to_Redshift_v3.py
[2022-01-19 12:10:00,214] {processor.py:171} INFO - Processing /opt/airflow/dags/MySQL_to_Redshift_v3.py took 0.066 seconds
